// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serivce.proto

package com.guan.sso.client.grpc.stub;

public interface LogoutReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.LogoutReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool real = 1;</code>
   */
  boolean getReal();
}
