// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serivce.proto

package com.guan.sso.client.grpc.stub;

public interface UserReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.UserReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 uid = 1;</code>
   */
  long getUid();
}
